$LAB
.wait(function(){
	$.jaygrid();
})
.wait(function(){
	$(".sortable").stupidtable();
})
.wait(function(){
	$(".sticky").headroom();
})
.wait(function(){
	$(".datepicker").pickadate();
})
.wait(function(){
	$(".timepicker").pickatime();
})
.wait(function(){
	$('textarea').elasticize();
})
.wait(function(){
	$(".fitvid").fitVids();
})
.wait(function(){
	$('input').iCheck({checkboxClass: 'icheckbox_flat-blue',radioClass: 'iradio_flat-blue'});
})
.wait(function(){
	$('.focuspoint').focusPoint();
});